# Generated by Django 4.0.3 on 2023-09-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technician',
            options={'ordering': ('first_name',)},
        ),
    ]
